### ISSUE TITLE
Include local graphic so it is shown on social media posts

### ISSUE THREAD

**Issue by cyclingzealot** [cyclingzealot/horkos#12]
> Date: jeu. 24 oct. 2019, à 21 h 51
> Subject: web graphic missing
> To: Julien Lamarche <julien.lamarche@gmail.com>
> 
> Hi Julien, when I post http://myvoteshouldcount.ca/ to Facebook, it uses a non-meaningful generic graphic because there's none for the webpage.
> 
> Please consider finding a graphic to add to that page.

**Comment by FredericGuilbault** [comment]
La localisation de l'image devrais etre: 
`http://campaign2015.fairvote.ca/wp-content/themes/fairvotecanada/images/slides/pr1.jpg`

Mais `campaign2015.fairvote.ca` n'existe plus. Je ne sait pas a quoi ressemblais `pr1.jpg`

Si vous en avez une copie en quelquepart je peut l'integrer depot actuel.
 
Si vous avez une image que vous aimeriez utiliser vous pouvez me la partager via http://imgur.com ou autre. 

Au pire, Je peut aussi prendre une capture d'ecran du site web et l'utiliser.

**Comment by cyclingzealot** [comment]
Merci pour ton temps. 

Je me demande si on regarde le même code / branche.

L'image à http://myvoteshouldcount.ca/  pointe à https://www.fairvote.ca/wp-content/uploads/2018/03/FVC-logo-cropped.jpg  .

Je crois que le serveur de production  est sur la branche cdn2019.  Je peux vérifier si nécéssaire.

**Comment by FredericGuilbault** [comment]
https://www.fairvote.ca/wp-content/uploads/2018/03/FVC-logo-cropped.jpg  est l"image affiché dans la page web. 

Mais horko demande a Facebook d'utiliser http://campaign2015.fairvote.ca/wp-content/themes/fairvotecanada/images/slides/pr1.jpg Via le tag `<meta>` nommé `og:image`

https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fmyvoteshouldcount.ca%2F

Je pourrais simplement le changer pour  https://www.fairvote.ca/wp-content/uploads/2018/03/FVC-logo-cropped.jpg si c'est la bonne image.

**Comment by cyclingzealot** [comment]
C'est certain que pr1.jpg était une plus belle image.   Mais ça prendrais trop de temps de chasser pour l'original.   Changeons og:image à logo-cropped.jpg pour l'instant.  Si moi ou toi on trouve une meilleur image, on le changera de nouveau.  Merci beaucoup!
