### ISSUE TITLE
Installing procedure arch archlinux

### ISSUE THREAD

**Issue by ghost** [cyclingzealot/horkos#5]
This is how i managed to install it under arch linux:

cd /usr/local/bin

curl -sS https://getcomposer.org/installer | php    

> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/gd.so' - /usr/lib/php/modules/gd.so: cannot open shared object file: No such file or directory in Unknown on line 0
> # !/usr/bin/env php

[border@localhost bin]$ sudo pacman -S php-gd

[border@localhost bin]$ curl -sS https://getcomposer.org/installer | php

> # !/usr/bin/env php
> 
> Some settings on your machine make Composer unable to work properly.
> Make sure that you fix the issues listed below and run this script again:
> The phar extension is missing.
> Install it or recompile php without --disable-phar

sudo nano  /etc/php/php.ini 
   uncomment phar.so

[border@localhost bin]$ sudo curl -sS https://getcomposer.org/installer | sudo php

> # !/usr/bin/env php
> 
> All settings correct for using Composer
> PHP Warning:  realpath(): open_basedir restriction in effect. File(/usr/local/bin) is not within the allowed path(s): 

sudo nano  /etc/php/php.ini 
    add :/ to open_basedir

[border@localhost bin]$ sudo curl -sS https://getcomposer.org/installer | sudo php

> # !/usr/bin/env php
> 
> All settings correct for using Composer
> Downloading...
> Composer successfully installed to: /usr/local/bin/composer.phar
> Use it: php composer.phar

sudo nano  /etc/php/php.ini 
    remove :/ from open_basedir
    add :/usr/local/bin/:/usr/bin/php

sudo tar -xzf data.tar.gz
sudo chown -R http horkos
sudo chmod -R g+w horkos    

edit and append horkos/doc/horkos2015.conf to /etc/httpd/httpd.conf
servicectl restart httpd

mkdir ~/log/
nohup horkos/eshu/cdn.bash &

**Comment by cyclingzealot** [comment]
Closed as per permission by email discussion with author at 26 octobre 2015 12:18.  Wanted install instructions to be publicly available.
