### ISSUE TITLE
byParty anchor does not seem to work

### ISSUE THREAD

**Issue by cyclingzealot** [cyclingzealot/horkos#7]
On 2015/12/15 at 03:51, the  anchor  http://myvoteshouldcount.ca/#byParty does not seem to work.

@border0464111

**Comment by ghost** [comment]
Confirmed,
Im super duper over busy this week, I will try to fix it this weekend.

**Comment by cyclingzealot** [comment]
No rush.  Election is over.  This can wait until new year.

Julien

## 

Make innovation easy
http://www.credil.org/

2015-12-15 9:20 GMT-05:00 border0464111 notifications@github.com:

**Comment by cyclingzealot** [comment]
Fixed in sk2014 branch
https://github.com/cyclingzealot/horkos/blob/e219a2b03fa44304d2b5466394221b04d53f34be/symfony/src/Jlam/HorkosBundle/Resources/views/Horkos/index.html.twig#L151
